/* tslint:disable */
/* eslint-disable */
/**
 * Meroku API Documentation
 * Open API specs for Meroku APIs. These APIs are required to inteact with the registry in a safe, easy way. The recommended way to use in a project is to use the npm package published at [@merokudao/storekit-sdk](https://www.npmjs.com/package/@merokudao/storekit-sdk). This npmjs package is a wrapper around the api. You would still want to use the APIs if you're building on a different platform.  # Authentication - To learn more on Authentication and the benefits of using higher rate limit, [read this Meroku.xyz blog post](https://meroku.xyz/2023/06/08/meroku-api-updates/). - To request an API key [fill this developer access form](https://form.jotform.com/231576486954067) - You can try this UI without getting any API Key as well # Learn More - [How to build a dApp Store using Meroku APIs](https://docs.meroku.org/dapp-store-kit-docs/for-dapp-store-builders#api--sdk-1) - [Meroku Blog](https://meroku.xyz) # Support - [Support Discourse Group](https://meroku.discourse.group) # Stay Connected - [Follow us on Github](https://github.com/merokudao) - [Follow us on Twitter](https://twitter.com/MerokuStore) 
 *
 * OpenAPI spec version: 1.27
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { InlineResponse2003 } from '../models';
import { InlineResponse2004 } from '../models';
import { InlineResponse2005 } from '../models';
/**
 * StoreRegistryApi - axios parameter creator
 * @export
 */
export const StoreRegistryApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Auto-Complete search
         * @param {string} search 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        autocompleteStores: async (search: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'search' is not null or undefined
            if (search === null || search === undefined) {
                throw new RequiredError('search','Required parameter search was null or undefined when calling autocompleteStores.');
            }
            const localVarPath = `/api/v1/store/autocomplete`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("apikey")
                    : await configuration.apiKey;
                localVarHeaderParameter["apikey"] = localVarApiKeyValue;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Get all stores or search by a keyword. Optionally, filter on specific attributes of the store. This API call will get all the store or perform a text search.
         * @summary Search Store
         * @param {number} [page] Current page
         * @param {number} [limit] Page size
         * @param {string} [search] A string to be used for search. The search happens on the &#x60;name&#x60; and &#x60;tags&#x60; fields of the dApp. If this is not present, all dApps are returned.
         * @param {Array<string>} [categories] The categories in which dApps belong. Multiple categories are joined using OR operator.
         * @param {boolean} [isListed] DApp is listed or not
         * @param {boolean} [isMinted] DApp is listed or not
         * @param {string} [language] DApp&#x27;s language
         * @param {Array<string>} [allowedInCountries] dApp allowed countries
         * @param {Array<string>} [blockedInCountries] dApp blocked countries
         * @param {boolean} [isForMatureAudience] Mentions if the app is for all ages or only mature audience
         * @param {number} [minAge] Minimum age
         * @param {string} [listedOnOrAfter] The date dApp was listed on or after. Date should be in ISO format.
         * @param {string} [listedOnOrBefore] The date dApp was listed on or before. Date should be in ISO format.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchStores: async (page?: number, limit?: number, search?: string, categories?: Array<string>, isListed?: boolean, isMinted?: boolean, language?: string, allowedInCountries?: Array<string>, blockedInCountries?: Array<string>, isForMatureAudience?: boolean, minAge?: number, listedOnOrAfter?: string, listedOnOrBefore?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/store/search`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("apikey")
                    : await configuration.apiKey;
                localVarHeaderParameter["apikey"] = localVarApiKeyValue;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (categories) {
                localVarQueryParameter['categories'] = categories;
            }

            if (isListed !== undefined) {
                localVarQueryParameter['isListed'] = isListed;
            }

            if (isMinted !== undefined) {
                localVarQueryParameter['isMinted'] = isMinted;
            }

            if (language !== undefined) {
                localVarQueryParameter['language'] = language;
            }

            if (allowedInCountries) {
                localVarQueryParameter['allowedInCountries'] = allowedInCountries;
            }

            if (blockedInCountries) {
                localVarQueryParameter['blockedInCountries'] = blockedInCountries;
            }

            if (isForMatureAudience !== undefined) {
                localVarQueryParameter['isForMatureAudience'] = isForMatureAudience;
            }

            if (minAge !== undefined) {
                localVarQueryParameter['minAge'] = minAge;
            }

            if (listedOnOrAfter !== undefined) {
                localVarQueryParameter['listedOnOrAfter'] = (listedOnOrAfter as any instanceof Date) ?
                    (listedOnOrAfter as any).toISOString().substr(0,10) :
                    listedOnOrAfter;
            }

            if (listedOnOrBefore !== undefined) {
                localVarQueryParameter['listedOnOrBefore'] = (listedOnOrBefore as any instanceof Date) ?
                    (listedOnOrBefore as any).toISOString().substr(0,10) :
                    listedOnOrBefore;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Search store By owner Address
         * @param {string} ownerAddress 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchStoresByOwnerAddress: async (ownerAddress: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ownerAddress' is not null or undefined
            if (ownerAddress === null || ownerAddress === undefined) {
                throw new RequiredError('ownerAddress','Required parameter ownerAddress was null or undefined when calling searchStoresByOwnerAddress.');
            }
            const localVarPath = `/api/v1/store/search/address/{ownerAddress}`
                .replace(`{${"ownerAddress"}}`, encodeURIComponent(String(ownerAddress)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("apikey")
                    : await configuration.apiKey;
                localVarHeaderParameter["apikey"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Search store By store Id
         * @param {string} storeId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchStoresByStoreId: async (storeId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'storeId' is not null or undefined
            if (storeId === null || storeId === undefined) {
                throw new RequiredError('storeId','Required parameter storeId was null or undefined when calling searchStoresByStoreId.');
            }
            const localVarPath = `/api/v1/store/search/{storeId}`
                .replace(`{${"storeId"}}`, encodeURIComponent(String(storeId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("apikey")
                    : await configuration.apiKey;
                localVarHeaderParameter["apikey"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * StoreRegistryApi - functional programming interface
 * @export
 */
export const StoreRegistryApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Auto-Complete search
         * @param {string} search 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async autocompleteStores(search: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse2005>>> {
            const localVarAxiosArgs = await StoreRegistryApiAxiosParamCreator(configuration).autocompleteStores(search, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Get all stores or search by a keyword. Optionally, filter on specific attributes of the store. This API call will get all the store or perform a text search.
         * @summary Search Store
         * @param {number} [page] Current page
         * @param {number} [limit] Page size
         * @param {string} [search] A string to be used for search. The search happens on the &#x60;name&#x60; and &#x60;tags&#x60; fields of the dApp. If this is not present, all dApps are returned.
         * @param {Array<string>} [categories] The categories in which dApps belong. Multiple categories are joined using OR operator.
         * @param {boolean} [isListed] DApp is listed or not
         * @param {boolean} [isMinted] DApp is listed or not
         * @param {string} [language] DApp&#x27;s language
         * @param {Array<string>} [allowedInCountries] dApp allowed countries
         * @param {Array<string>} [blockedInCountries] dApp blocked countries
         * @param {boolean} [isForMatureAudience] Mentions if the app is for all ages or only mature audience
         * @param {number} [minAge] Minimum age
         * @param {string} [listedOnOrAfter] The date dApp was listed on or after. Date should be in ISO format.
         * @param {string} [listedOnOrBefore] The date dApp was listed on or before. Date should be in ISO format.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchStores(page?: number, limit?: number, search?: string, categories?: Array<string>, isListed?: boolean, isMinted?: boolean, language?: string, allowedInCountries?: Array<string>, blockedInCountries?: Array<string>, isForMatureAudience?: boolean, minAge?: number, listedOnOrAfter?: string, listedOnOrBefore?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse2003>>> {
            const localVarAxiosArgs = await StoreRegistryApiAxiosParamCreator(configuration).searchStores(page, limit, search, categories, isListed, isMinted, language, allowedInCountries, blockedInCountries, isForMatureAudience, minAge, listedOnOrAfter, listedOnOrBefore, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Search store By owner Address
         * @param {string} ownerAddress 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchStoresByOwnerAddress(ownerAddress: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse2004>>> {
            const localVarAxiosArgs = await StoreRegistryApiAxiosParamCreator(configuration).searchStoresByOwnerAddress(ownerAddress, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Search store By store Id
         * @param {string} storeId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchStoresByStoreId(storeId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InlineResponse2004>>> {
            const localVarAxiosArgs = await StoreRegistryApiAxiosParamCreator(configuration).searchStoresByStoreId(storeId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * StoreRegistryApi - factory interface
 * @export
 */
export const StoreRegistryApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Auto-Complete search
         * @param {string} search 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async autocompleteStores(search: string, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse2005>> {
            return StoreRegistryApiFp(configuration).autocompleteStores(search, options).then((request) => request(axios, basePath));
        },
        /**
         * Get all stores or search by a keyword. Optionally, filter on specific attributes of the store. This API call will get all the store or perform a text search.
         * @summary Search Store
         * @param {number} [page] Current page
         * @param {number} [limit] Page size
         * @param {string} [search] A string to be used for search. The search happens on the &#x60;name&#x60; and &#x60;tags&#x60; fields of the dApp. If this is not present, all dApps are returned.
         * @param {Array<string>} [categories] The categories in which dApps belong. Multiple categories are joined using OR operator.
         * @param {boolean} [isListed] DApp is listed or not
         * @param {boolean} [isMinted] DApp is listed or not
         * @param {string} [language] DApp&#x27;s language
         * @param {Array<string>} [allowedInCountries] dApp allowed countries
         * @param {Array<string>} [blockedInCountries] dApp blocked countries
         * @param {boolean} [isForMatureAudience] Mentions if the app is for all ages or only mature audience
         * @param {number} [minAge] Minimum age
         * @param {string} [listedOnOrAfter] The date dApp was listed on or after. Date should be in ISO format.
         * @param {string} [listedOnOrBefore] The date dApp was listed on or before. Date should be in ISO format.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchStores(page?: number, limit?: number, search?: string, categories?: Array<string>, isListed?: boolean, isMinted?: boolean, language?: string, allowedInCountries?: Array<string>, blockedInCountries?: Array<string>, isForMatureAudience?: boolean, minAge?: number, listedOnOrAfter?: string, listedOnOrBefore?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse2003>> {
            return StoreRegistryApiFp(configuration).searchStores(page, limit, search, categories, isListed, isMinted, language, allowedInCountries, blockedInCountries, isForMatureAudience, minAge, listedOnOrAfter, listedOnOrBefore, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Search store By owner Address
         * @param {string} ownerAddress 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchStoresByOwnerAddress(ownerAddress: string, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse2004>> {
            return StoreRegistryApiFp(configuration).searchStoresByOwnerAddress(ownerAddress, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Search store By store Id
         * @param {string} storeId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchStoresByStoreId(storeId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<InlineResponse2004>> {
            return StoreRegistryApiFp(configuration).searchStoresByStoreId(storeId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * StoreRegistryApi - object-oriented interface
 * @export
 * @class StoreRegistryApi
 * @extends {BaseAPI}
 */
export class StoreRegistryApi extends BaseAPI {
    /**
     * 
     * @summary Auto-Complete search
     * @param {string} search 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StoreRegistryApi
     */
    public async autocompleteStores(search: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse2005>> {
        return StoreRegistryApiFp(this.configuration).autocompleteStores(search, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Get all stores or search by a keyword. Optionally, filter on specific attributes of the store. This API call will get all the store or perform a text search.
     * @summary Search Store
     * @param {number} [page] Current page
     * @param {number} [limit] Page size
     * @param {string} [search] A string to be used for search. The search happens on the &#x60;name&#x60; and &#x60;tags&#x60; fields of the dApp. If this is not present, all dApps are returned.
     * @param {Array<string>} [categories] The categories in which dApps belong. Multiple categories are joined using OR operator.
     * @param {boolean} [isListed] DApp is listed or not
     * @param {boolean} [isMinted] DApp is listed or not
     * @param {string} [language] DApp&#x27;s language
     * @param {Array<string>} [allowedInCountries] dApp allowed countries
     * @param {Array<string>} [blockedInCountries] dApp blocked countries
     * @param {boolean} [isForMatureAudience] Mentions if the app is for all ages or only mature audience
     * @param {number} [minAge] Minimum age
     * @param {string} [listedOnOrAfter] The date dApp was listed on or after. Date should be in ISO format.
     * @param {string} [listedOnOrBefore] The date dApp was listed on or before. Date should be in ISO format.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StoreRegistryApi
     */
    public async searchStores(page?: number, limit?: number, search?: string, categories?: Array<string>, isListed?: boolean, isMinted?: boolean, language?: string, allowedInCountries?: Array<string>, blockedInCountries?: Array<string>, isForMatureAudience?: boolean, minAge?: number, listedOnOrAfter?: string, listedOnOrBefore?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse2003>> {
        return StoreRegistryApiFp(this.configuration).searchStores(page, limit, search, categories, isListed, isMinted, language, allowedInCountries, blockedInCountries, isForMatureAudience, minAge, listedOnOrAfter, listedOnOrBefore, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Search store By owner Address
     * @param {string} ownerAddress 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StoreRegistryApi
     */
    public async searchStoresByOwnerAddress(ownerAddress: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse2004>> {
        return StoreRegistryApiFp(this.configuration).searchStoresByOwnerAddress(ownerAddress, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Search store By store Id
     * @param {string} storeId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StoreRegistryApi
     */
    public async searchStoresByStoreId(storeId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<InlineResponse2004>> {
        return StoreRegistryApiFp(this.configuration).searchStoresByStoreId(storeId, options).then((request) => request(this.axios, this.basePath));
    }
}
