/* tslint:disable */
/* eslint-disable */
/**
 * Meroku dApp store
 * Open API specs for Meroku DApp store. This documentation is the guide to Backend API. These APIs are required to build the frontend.  You can choose to build on top of this API or use the npm package available at [some link](https://www.example.com)  **Authentication**  The endpoints themselves are public. The CORS policy restricts browser usage beyond `*.meroku.store`. This means that you can use these APIs in your backend services, but if called directly from frontend, it has to be hosted at *.meroku.store.  The `GET` calls are public without rate limiting.  The `POST`, `UPDATE`, `DELETE` calls ensure that only the dApp developer can make changes to their own dApp listing. This is done by sending the Github (user - server) token in these API calls. The mechanism to get the Github access tokens is up to the frontend to decide. They can for example create a Github App or use a service like Auth0.  In this server, you will be able to see your github details on the top left. You can use those details to enter values in the update calls.   **FAQs**  1. I am getting a `400 Resource not accessible by integration` error on update calls. This can happen when the github token supplied does not have valid permissions. Ensure that you are not sending `org` param. Right now, the fork can only happen on individual and not at org level.   2. I am getting a `400 Not Found` error on update calls. Ensure that you are passing the correct github ID or the user who wants to make the update.
 *
 * OpenAPI spec version: 1.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { Dapp } from '../models';
/**
 * StoreRegistryApi - axios parameter creator
 * @export
 */
export const StoreRegistryApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * For finding featured dApps
         * @summary Featured dApps
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFeaturedDApps: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/store/featured`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns the store title
         * @summary Registry title
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStoreTitle: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/store/title/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * StoreRegistryApi - functional programming interface
 * @export
 */
export const StoreRegistryApiFp = function(configuration?: Configuration) {
    return {
        /**
         * For finding featured dApps
         * @summary Featured dApps
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getFeaturedDApps(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<Dapp>>>> {
            const localVarAxiosArgs = await StoreRegistryApiAxiosParamCreator(configuration).getFeaturedDApps(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Returns the store title
         * @summary Registry title
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStoreTitle(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<string>>> {
            const localVarAxiosArgs = await StoreRegistryApiAxiosParamCreator(configuration).getStoreTitle(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * StoreRegistryApi - factory interface
 * @export
 */
export const StoreRegistryApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * For finding featured dApps
         * @summary Featured dApps
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getFeaturedDApps(options?: AxiosRequestConfig): Promise<AxiosResponse<Array<Dapp>>> {
            return StoreRegistryApiFp(configuration).getFeaturedDApps(options).then((request) => request(axios, basePath));
        },
        /**
         * Returns the store title
         * @summary Registry title
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStoreTitle(options?: AxiosRequestConfig): Promise<AxiosResponse<string>> {
            return StoreRegistryApiFp(configuration).getStoreTitle(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * StoreRegistryApi - object-oriented interface
 * @export
 * @class StoreRegistryApi
 * @extends {BaseAPI}
 */
export class StoreRegistryApi extends BaseAPI {
    /**
     * For finding featured dApps
     * @summary Featured dApps
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StoreRegistryApi
     */
    public async getFeaturedDApps(options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<Dapp>>> {
        return StoreRegistryApiFp(this.configuration).getFeaturedDApps(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Returns the store title
     * @summary Registry title
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StoreRegistryApi
     */
    public async getStoreTitle(options?: AxiosRequestConfig) : Promise<AxiosResponse<string>> {
        return StoreRegistryApiFp(this.configuration).getStoreTitle(options).then((request) => request(this.axios, this.basePath));
    }
}
